import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { ff } from "./utils/actions";
import { StoreEntity } from "feeef";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch store Using FeeeF Core API By Slug (Subdomain)

  const store: StoreEntity | null = await ff.stores.find({
    id: "asynx",
    by: "slug",
  });
  // Example of fetching store by ID

  // Fetch Products Using FeeeF Core API By Store ID
  const products = await ff.products.list({
    params: {
      store_id: store.id,
    },
  });

  console.log(products);
  console.log(store);
  return (
    <html lang="ar">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
