// app/middleware.ts
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

// DO NOT EDIT THIS FILE

export async function middleware(req: NextRequest) {
  const { hostname } = req.nextUrl;
  const response = NextResponse.next();
  if (hostname === "localhost" || hostname === "127") {
    response.headers.set("x-tenant-subdomain", "melissa");
    return response;
  }

  let subdomain = hostname.split(".")[0];
  if (subdomain === "www") {
    subdomain = hostname.split(".")[1];
  }

  response.headers.set("x-tenant-subdomain", "melissa"); // CHANGE THIS TO  SUBDOMAIN VARIABLE TO DYNAMICALLY SET SUBDOMAIN

  return response;
}
// To apply middleware globally, ensure that the `middleware.ts` is in the root of `app` directory
